inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'docs/**/*'
    - 'examples/**/*'
    - 'vendor/bundle/**/*'

Layout/CommentIndentation:
  AllowForAlignment: true
